apt-get install vim -y
apt-get install fswatch -y
apt-get install p7zip-full -y
apt-get install cmake -y
apt-get install net-tools -y
apt-get install tmux -y
apt-get install gawk -y
apt-get install tree -y
apt-get install flex -y
apt-get install bison -y
apt-get install exfat-utils -y
apt-get install httrack -y
apt-get install fcitx-bin -y
apt-get install fcitx-table -y
apt-get install ttf-mscorefonts-installer -y
apt-get install fontconfig
apt-get install terminator -y
apt-get install lua5.3 -y
apt-get install curl -y
apt-get install fzf -y
apt-get install expect -y
apt-get install openjdk-8-jdk -y
apt-get install nodejs -y